### API INSTRUMENTO - GET
GET http://localhost:8080/api/v1/instrumento
Content-Type: application/json

### API INSTRUMENTO - POST
POST http://localhost:8080/api/v1/instrumento
Content-Type: application/json

{
    "id": 0,
    "nome": "Violão",
    "tipo": "Cordas",
    "codigo": "F310",
    "sobressalentes": true
}

### API INSTRUMENTO - PUT
PUT http://localhost:8080/api/v1/instrumento/1
Content-Type: application/json

{
    "nome": "Violão grande",
    "tipo": "Cordas",
    "codigo": "F310",
    "sobressalentes": false
}

### API INSTRUMENTO - DELETE
DELETE http://localhost:8080/api/v1/instrumento/1
Content-Type: application/json

{
    
}