### API INSTRUMENTO - GET
GET http://localhost:8080/api/v1/instrumento
Content-Type: application/json

### API INSTRUMENTO - POST
POST http://localhost:8080/api/v1/instrumento
Content-Type: application/json

{
    "nome": "Violão",
    "tipo": "Cordas",
    "codigo": "F310",
    "sobressalentes": true,
    "aluno": {
        "id": 1,
        "nome": "João",
        "endereco": "Rua A, 123",
        "telefone": "123456789",
        "email": "joao@gmail.com",
        "dataNascimento": "2000-01-01",
        "cpf": "12345678901",
        "sexo": "F"
    }
}

### API INSTRUMENTO - PUT
PUT http://localhost:8080/api/v1/instrumento/1
Content-Type: application/json

{
    "nome": "Violão grande",
    "tipo": "Cordas",
    "codigo": "F310",
    "sobressalentes": false,
    "aluno": {
        "id": 1,
        "nome": "João",
        "endereco": "Rua A, 123",
        "telefone": "123456789",
        "email": "joao@gmail.com",
        "dataNascimento": "2000-01-01",
        "cpf": "12345678901",
        "sexo": "F"
    }
}

### API INSTRUMENTO - DELETE
DELETE http://localhost:8080/api/v1/instrumento/1
Content-Type: application/json

{
    
}